CC      = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
SIZE    = arm-none-eabi-size

# Project Structure
ROOTDIR := $(CURDIR)
LIBDIR   = $(ROOTDIR)/lib
BUILD_DIR = build

# Source Files
SRCS = main.c $(wildcard $(LIBDIR)/*.c)
# Transform source paths to object paths in the build directory
OBJS = $(addprefix $(BUILD_DIR)/, $(notdir $(SRCS:.c=.o)))
# Transform object paths to dependency paths
DEPS = $(OBJS:.o=.d)

# Search paths for source files (so make can find them)
vpath %.c . $(LIBDIR)

# Compiler Flags
# -MMD -MP: Generate dependency files
# -fno-strict-aliasing: Safe for union/struct pointer casting
CFLAGS += -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16
CFLAGS += -W -Wall -Wextra -Werror -Wundef -Wshadow -Wdouble-promotion \
          -Wformat-truncation -fno-common -Wconversion -fno-strict-aliasing \
          -g3 -Og -ffunction-sections -fdata-sections -MMD -MP \
          -I. -I$(LIBDIR) 

# Linker Flags
LDFLAGS += -Tf411.ld -nostartfiles -nostdlib --specs nano.specs \
           -lc -lgcc -Wl,--gc-sections -Wl,-Map=$(BUILD_DIR)/firmware.map

# --- Rules ---

all: $(BUILD_DIR)/firmware.bin
	@echo "\n--- Build Summary ---"
	$(SIZE) $(BUILD_DIR)/firmware.elf

# Build Binary
$(BUILD_DIR)/firmware.bin: $(BUILD_DIR)/firmware.elf
	$(OBJCOPY) -O binary $< $@

# Link ELF
$(BUILD_DIR)/firmware.elf: $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) $(LDFLAGS) -o $@

# Compile C Files
$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Create build directory if it doesn't exist
$(BUILD_DIR):
	mkdir -p $@

flash: $(BUILD_DIR)/firmware.bin
	sudo st-flash --reset write $< 0x8000000

clean:
	rm -rf $(BUILD_DIR)

# Include dependencies generated by GCC
-include $(DEPS)

.PHONY: all clean flash